# Generated by Django 3.1 on 2020-11-27 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201127_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelisting',
            name='watcher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='listwatcher', to=settings.AUTH_USER_MODEL),
        ),
    ]
